// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDII1c7sAlLAf2tiDeCyC72SRVIASQ4rq4',
    appId: '1:882601206900:web:21487b66ab7d6db9275d21',
    messagingSenderId: '882601206900',
    projectId: 'alert-aid-app',
    authDomain: 'alert-aid-app.firebaseapp.com',
    storageBucket: 'alert-aid-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-iwnDLxsyLklDl2XI8LsWiA81X6QXu9g',
    appId: '1:882601206900:android:a5e4900f3399c011275d21',
    messagingSenderId: '882601206900',
    projectId: 'alert-aid-app',
    storageBucket: 'alert-aid-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuU7YiqZ_aFnuQDPL6j-VbeFJHeTkf72c',
    appId: '1:882601206900:ios:4b00c44b586bccb3275d21',
    messagingSenderId: '882601206900',
    projectId: 'alert-aid-app',
    storageBucket: 'alert-aid-app.firebasestorage.app',
    iosBundleId: 'com.example.disasterManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuU7YiqZ_aFnuQDPL6j-VbeFJHeTkf72c',
    appId: '1:882601206900:ios:4b00c44b586bccb3275d21',
    messagingSenderId: '882601206900',
    projectId: 'alert-aid-app',
    storageBucket: 'alert-aid-app.firebasestorage.app',
    iosBundleId: 'com.example.disasterManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDII1c7sAlLAf2tiDeCyC72SRVIASQ4rq4',
    appId: '1:882601206900:web:4eeaaf21446e34f3275d21',
    messagingSenderId: '882601206900',
    projectId: 'alert-aid-app',
    authDomain: 'alert-aid-app.firebaseapp.com',
    storageBucket: 'alert-aid-app.firebasestorage.app',
  );
}
